/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bjsxt.study.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 
 */
public enum RespCode implements org.apache.thrift.TEnum {
  Success(0),
  Failed(400),
  Error(500);

  private final int value;

  private RespCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RespCode findByValue(int value) { 
    switch (value) {
      case 0:
        return Success;
      case 400:
        return Failed;
      case 500:
        return Error;
      default:
        return null;
    }
  }
}
